### ISSUE TITLE
QA: Spacing & RSB

### ISSUE THREAD

**Issue by PichottaFB** [TypeNetwork/fb-Amstelvar#1]
Style: **GradeMax**

The fit is non-symmetrical with outlines shifted right on setwidth, or the rsb not set. ?

**Comment by asaumierdemers** [comment]
@PichottaFB This Grade axis was generated by script, using the ParaWeight axis together with the Width axis. I improved the script to keep the same side bearing ratio as the Default master, while keeping the same width. Can you have a look a this new version?

[AmstelvarAlpha-GradeMax.ufo.zip](https://github.com/TypeNetwork/fb-Amstelvar/files/705268/AmstelvarAlpha-GradeMax.ufo.zip)

**Comment by dberlow** [comment]
I've made corrections to the A-Z, a-z and 0-9 of this size pole.
