### ISSUE TITLE
Fix: Dollar sign

### ISSUE THREAD

**Issue by asaumierdemers** [TypeNetwork/fb-Amstelvar#11]

**Comment by davelab6** [comment]
Width = max:
<img width="508" alt="screen shot 2017-06-18 at 14 44 30" src="https://user-images.githubusercontent.com/261579/27263328-b8a752ae-5434-11e7-969e-c8579a01d53e.png">

Width = min:

<img width="427" alt="screen shot 2017-06-18 at 14 44 54" src="https://user-images.githubusercontent.com/261579/27263327-b8a674ba-5434-11e7-810a-63eeed16b108.png">

Width = any other value:

<img width="388" alt="screen shot 2017-06-18 at 14 44 09" src="https://user-images.githubusercontent.com/261579/27263326-b8a30438-5434-11e7-977d-8f69ee9751da.png">
