### ISSUE TITLE
Website: Update illustration to prevent counter of (1) changing

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/fb-Amstelvar#18]
In https://www.typenetwork.com/brochure/opentype-variable-fonts-moving-right-along the first illustration, marked 1, is not right; it shows the counterform changing, but it should not, I believe.

**Comment by dberlow** [comment]
Yes. I believe we have replaced the paraweight min, but perhaps not updated the gift.

**Comment by asaumierdemers** [comment]
<img width="556" alt="screen shot 2017-07-05 at 4 23 58 pm" src="https://user-images.githubusercontent.com/5811246/27883419-64d80b38-619e-11e7-883c-dc907ba716bd.png">

Fixed!

You might need to wait until the cache is cleared to see the update.
