### ISSUE TITLE
Amstelvar proofing algorithm

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/fb-Amstelvar#19]
Here's a start for reality check that specifies only the first al all but the specific combos required, to make sure I've covered all the major areas of proofing variables

Let me know.

Amstelvar proofing process
0. proof control characters
1. proof parametirc axis.
2. analyze and correct 
3. Reproof parametirc axis, repeat 2 if req.
4. proof registered axis.
5. 2 & 3 to completion.

Amstelvar axes, proofing granularity

Parametric Axes
A. Contrast, 10% (means dividing the axis into ten equal parts and proofing just those).
B. X-height, 10%
C. ParaWeight, 10%
D. Parawidth, 10%
E. Serif Rise, NA

Registered axies (blended)
F. Width 10%
G. Weight 10%
H. Optical Size, 
   (Range 1, 8pt, 10pt, 12 pt, 14), 
   (Range 2, 18pt, 20, 24, 30, 36), 
   (Range 3, 42pt, 48, 56, 64), 
   (Range 4, 72pt, 100, 128, 144)

Blended Axis
I. Grade
   (Range 1, 8pt, 10pt, 12 pt, 14), 20%
   (Range 2, 18pt, 20, 24, 30, 36), 10%

Amstelvar proofing Texts

Text#    Text      
1. Aa1

2. HHDHOHODOO0010111

3. ABCDEFGHIJKLMNOPQRSTUVWXYZ
    abcdefghijklmnopqrstuvwxyz
    1023456789.,:;!?&

4. 3 + remainder of glyphs in font broken at A to Z’s line length

5. 3 between H’s

6. 3 between n’s

7. 4 between H’s

8. 4 between n’s

9. MAY BROUGHT BACK FIVE OR SIX DOZEN PIECES OF OUR QUEEN’S JEWELLERY. [broken at A to Z’s line length]

10. Calligraphy requires just a few very basic needs: pen, ink, dexterity and most of all, zeal. [broken at A to Z’s line length]

11. THE BASQUE M.P. LOVED HIS WIFE’S ONYX JAR AND ZINC-LINED KEG. I HAVE QUICKLY SPOTTED THE FOUR WOMEN DOZING IN THE JURY BOX. JUDGE POWER QUICKLY GAVE THE SIX EMBEZZELERS STIFF SENTENCES. MAY BROUGHT BACK FIVE OR SIX DOZEN PIECES OF OUR QUEEN’S JEWELLERY. [broken at A to Z’s line length]

12. Calligraphy requires just a few very basic needs: pen, ink, dexterity and most of all, zeal. Curious and wily journalists braved the fury of the six brazen knaves picketing the mad queen. Justly vexed, the queen exiled the calligrapher who spattered black sumi ink on her fuzzy dog. Typography is known for two-dimensional architecture and requires extra zeal within every job. Their very kind aunt was subject to frequent dizzy spells, thus causing much anxiety and worry. The daredevils quivered, knowing that Rob would commit the faux pas of dozing when they jumped. 800-243-1759 [broken ragged unhyphenated at A to Z’s line length per specimen]

Amstelvar proofing combinations

Amstelvar proofing process
0. proof control characters
    A. Each Parametric Axis, at preferred granularity of each, using proof text #2
    B. Each Parametric Axis, at preferred granularity of each, using proof text #3
   …to be completed on agreement to this...

1. proof parametirc axis.
2. analyze and correct 
3. Reproof parametirc axis, repeat 2 if req.
4. proof registered axis.
5. 2 & 3 to completion.

**Comment by sberlow** [comment]
Is this a specification for a general proofing tool using Amstelvar as the test case?
