### ISSUE TITLE
QA: Vert Metrics,  xheight

### ISSUE THREAD

**Issue by PichottaFB** [TypeNetwork/fb-Amstelvar#2]
Do you want all xheight values to equal 1000? or do you want them to be aligned with the lc 'x'?  See the difference between the styles "**WeightMax**" vs. "WeightMin".

**Comment by asaumierdemers** [comment]
For the WeightMax we are increasing the xHeight like in a regular weight axis.
@dberlow is this correct?

**Comment by dberlow** [comment]
Yes.
