### ISSUE TITLE
A, Q, e have winding direction issues?

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/fb-Amstelvar#22]
The TTF committed today appears to have direction issues in a few glyphs:

![screen shot 2017-03-27 at 20 04 43](https://cloud.githubusercontent.com/assets/261579/24383085/b7d4543c-1328-11e7-975e-cbd3696fbf35.png)

**Comment by dberlow** [comment]
This is the second time someone has flagged this issue. What is showing this please

I will check them to make sure. 

But, enclosed are two apps that are compliant, and they are the only ones in which this Alpha has been tested. Do you want us to make variation fonts that work in legacy apps and OS that are non-compliant with TT standards?
![no overlaps](https://cloud.githubusercontent.com/assets/1956494/24383611/f2ffee7e-132b-11e7-8576-49205ab945fe.png)

**Comment by davelab6** [comment]
This was apparent in the Apple OS X 10.11 Finder, but this appears to be a (known) bug in the OS X rendering stack. 

I double checked and your font is good, boss :)
