### ISSUE TITLE
website/index.html needs to be updated for new filename, axis extents, axis names

### ISSUE THREAD

**Issue by Lorp** [TypeNetwork/fb-Amstelvar#24]
The website/index.html seems to be referring to an old version of the font. Specifically:

* the font filename (line 8) should be "../fonts/AmstelvarAlpha-VF.ttf"
* the axis extents are wrong (e.g. axis 'wght' has min: 75, default: 176, max: 500 when the current font has min: 38, default: 88, max: 250
* the axis names are wrong (e.g. the axis 'prwg' is not in the current font and is not a valid axis name, and the current font's axis 'XOPQ', among others, is not controlled)

**Comment by asaumierdemers** [comment]
@Lorp you are right, I didn't update the website after changing the font name and the axis values.
It's fixed now!
