### ISSUE TITLE
Add new 'parametric' axes

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/fb-Amstelvar#25]
Add new 'parametric' axes "as-is", to allow blending to be done by js/css

I think this will make the gestalt system more transparent/understandable for web development professionals to play around with and seek enlightenment - who are the current stage target market, the "innovators" in the first segment of the adoption bell curve. 

![technology-adoption-curve](https://user-images.githubusercontent.com/261579/26945356-7bd5d144-4c59-11e7-8bc3-15556bf87a04.png)

**Comment by asaumierdemers** [comment]
@davelab6 what do you mean by this issue?
new 'paramatric' axes "as-is"?

**Comment by dberlow** [comment]
funny, I just had exactly the same idea. to feed the raw font to a pdf that
knows the registered axis, and the bounds of each axis.

I have three of those now.;)

**Comment by davelab6** [comment]
Fixed in 

0b0448bd7f2bebd7dccdc580eb764f142268b91a
0fd5a9bb6b26bf08614108ba844a34ceb33a38b3
fb7d985f913593a777584511bc4ca3d603c6a97b
64e949ccd0220c92fe3cef20e9f89ba5ebe4415b
