### ISSUE TITLE
Flag appropriate axes as HIDDEN_AXIS

### ISSUE THREAD

**Issue by Lorp** [TypeNetwork/fb-Amstelvar#29]
Now that the HIDDEN_AXIS flag is [part of the spec](https://www.microsoft.com/typography/otspec/fvar.htm), it would be great if Amstelvar flagged those axes it doesn’t intend users to play with.

Related: I’m adding code to Axis-Praxis to hide hidden axes by default.

**Comment by Lorp** [comment]
Update: support for hidden axes is now in Axis-Praxis.

See https://twitter.com/axis_praxis/status/918898929734955013

**Comment by dberlow** [comment]
Amstelvar requires no modification for this supported addition.

The definition of "user" makes it so that many current and future fonts will have a "maybe" with regards to hidden axes, depending on the user, if not utterly neutering the usefulness of this flag, then pretty close.

**Comment by Lorp** [comment]
Indeed everything’s currently grey as currently there are no apps with users or user interfaces to consider. With your talk of “figuring” around Amstelvar, I had assumed that some of its axes were not for human grappling.
