### ISSUE TITLE
QA: Spacing Symmetry of Control Chars

### ISSUE THREAD

**Issue by PichottaFB** [TypeNetwork/fb-Amstelvar#5]
"**OpticalSizeMax**"
D - in other styles the rsb of 'D' is exactly the same as 'O'
o - o: (48, 47)

"**wdth84-wght10**"
See other Issue #7 about difference of fit of UC and lc rounds.

"**WeightMin**"
D - in other styles the rsb of 'D' is exactly the same as 'O' 

Some of these may be the rounding of only a unit depending how they were derived. If they are an intermediate then it is probably better to "let the points fall where they may".

"**WeightMax**"
O: (50, 49)
D: (51, 50)
zero: (46, 47)
o: (40, 39)

"**WeightMin**"
o: (93, 92)

**Comment by asaumierdemers** [comment]
Since these are only 1 unit off, "let the points fall where they may".
They are all generated masters and will probably be generated again :)

**Comment by PichottaFB** [comment]
Yes, also too because they will be scaled. These fall into my newly assigned 'guti' category. "get used to it" ;)
