### ISSUE TITLE
QA: Mirrored Glyphs

### ISSUE THREAD

**Issue by PichottaFB** [TypeNetwork/fb-Amstelvar#6]
In "**OpticalSizeMin**"

The "parenleft" and "parenright" are not composites and so are not mirror images of one another.  Do you care if the endings of the parentheses are slightly different angles?

**Comment by asaumierdemers** [comment]
OpticalSizeMin is generated from a combination of ParaWeight, xHeight and Contrast. The error was in ContrastMax and is now fixed. I will regenerate OpticalSizeMin.
