### ISSUE TITLE
QA: Spacing of 'O' vs. 'o'

### ISSUE THREAD

**Issue by PichottaFB** [TypeNetwork/fb-Amstelvar#7]
"**AmstelvarAlpha-wdth84-wght10**"

I am wondering why the fit of the Uppercase rounds are considerably tighter than the lowercase rounds?

I am also wondering about the spacing between the vertical upright and the sidebearings.  See for example the setting 'MNOPQ'.  Right side of 'P' also slightly tight with 'S' and 'n'

I can't quite figure out the rule of stem weights of diagonal chars. See 'K', 'M', 'N', 'R' ?

**Comment by asaumierdemers** [comment]
Sources updated
